### ISSUE TITLE
[여름방학 시즌] DKU Javascript Study Level 01 - 1기 모집

### ISSUE THREAD

**Issue by JunilHwang** [DKU-STUDY/recruit#1]
## Introduction
- 여름 방학 동안 프론트엔드 개발 역량 강화를 위해 자바스크립트 스터디를 모집합니다.

## 스터디 리더 소개
- 단국대 소프트웨어학과 2020년도 졸업생
- Java/Nodejs/Javascript/VueJS 등을 현업에서 사용중인 풀 스택 개발자
- [DKU-STUDY](https://github.com/DKU-STUDY) 멘토
- 블로그: http://junil-hwang.com/
- TIL: https://junilhwang.github.io/TIL
- github: https://github.com/junilhwang
- 2019년도 기준 자기소개 겸 발표 문서: http://junil-hwang.com/20191210.pdf
- 2020년 회고: https://junilhwang.github.io/TIL/Review/2020-year/end/
- [우아한 테크캠프 Pro 2](https://edu.nextstep.camp/s/ffeVDScX) 리뷰어 

## 스터디 일정
- 마감: 6/21(월)
- 시작: 6/21(월) 예상
- 종료: 7/19(월) 예상
- 최대 참가 인원: 10명

## 자격요건
- 자바스크립트에 관심이 있는 사람
- 자바스크립트를 좋아 하는 사람
- 웹 개발에 관심이 있는 사람
- 프론트엔드 개발자를 목표로 하고 싶은 사람
- React, Vue 같은 프레임워크에 초점을 두는게 아닌 Javascript 자체를 공부해보고 싶은 사람
- 최종적으로 프레임워크를 만들어보고 싶은 사람
- 같이 공부할 사람이 필요한 사람
- 방학기간에 뭐라도 해보고 싶은 사람

## 참가조건
- 참가비: 3만원
- 스터디를 무사 완주시 5만원으로 돌려드립니다

## 스터디 참여 방법
- github id가 필요합니다.
- 현재 issue card(https://github.com/DKU-STUDY/recruit/issues/1)에 comment로 참가의사를 남겨주세요.
  - 이름
  - 이메일 혹은 노출되도 무관한 연락처
  - 짤막한 자기 소개
  - 스터디에 기대하는 점

## 스터디 구성

- 커리큘럼
  - 1주차: Todo List 만들기
  - 2주차: Webpack + TodoList 리팩토링
  - 3주차: ExpressJS로 API 서버 만들기
  - 4주차: API 연동
  - 5주차: 배포하기

- 커리큘럼 외
  - (1) 매주 정해진 요일에 온라인 세션 진행
    - 1주차: 스터디에 대한 소개, 미션에 대한 소개 진행
    - 2 ~ 5주차: 미션에 대한 회고, 핵심내용, 좋은점, 아쉬운점 등에 대해 이야기
    - 스터디 리더가 이전 미션에 대해 빠르게 시연
    - 모든 온라인 세션은 녹화본 제공 예정
  - (2) 온라인 세션 후 일주일 동안 미션 진행
  - (3) Pull Request 를 올리면 코드 리뷰 진행
- 매일 밤 9시(혹은 최대한 많은 사람이 참여 가능한 시간)에 모여서 소소한 회고 및 질의응답을 진행합니다.

## 완주 후 혜택
- Level 2 과정 참여 자격 부여
- Level 1 리뷰어 활동 자격 부여 및 소정의 활동비 지급
- 학업 및 진로에 대한 상담 언제든 환영
- 완주 한 사람들과 소소한 식사 (선택)

**Comment by JunilHwang** [comment]
- 이름: 황준일
- 이메일: junil.h@kakao.com
- 짤막한 자기 소개
  - 저는 현재 [줌인터넷](https://zuminternet.com)에 근무하고 있는 황준일입니다.
  - 이 스터디의 리더입니다.
  - 단국대 학생들과 꾸준히 소통하고 싶어서 이러한 스터디를 만들었습니다. 
- 스터디에 기대하는 점
  - 무사 완주 하는 사람이 한 명 쯤은 있겠지!?

**Comment by Hanssoy** [comment]
- 이름 : 한소연
- 이메일 : soyeonesther@naver.com 
- 짤막한 자기소개 : 
소프트웨어학과 2학년 한소연입니다.
잘은 못하지만 열심히 하는 스타일입니다.
- 스터디에 기대하는 점 : 
javascript 언어를 혼자 공부하는 것도 좋지만 
미션을 해결하는 재미도 생기고 다른 사람들과 
같이 공부할 수 있는 기회가 생겨서 기대됩니다!

**Comment by cksgnlcjswo** [comment]
이름: 김찬휘
이메일: cksgnlcjswoo@naver.com
짤막한 자기 소개
소프트웨어학과 4학년 재학중인 김찬휘라고합니다
마침 이번 방학에 웹을 배우고 싶었는데 좋은 기회가 온것 같아서 신청하게되었습니다
완주를 목표로 열심히 해보겠습니다.
스터디에 기대하는 점
깃헙까지 다루는거 같아서 매우 기대됩니다.

**Comment by pul8219** [comment]
- 이름: 박유림
- 이메일: pul8219@naver.com
- 자기 소개: 소프트웨어학과 졸업예정인 박유림이라고 합니다. 웹 개발자 취업을 준비하고 있는데 Javascript를 탄탄히 다지고 배포까지 해보고싶어서 신청하게 되었습니다. 특히 다른 팀원들과 같이 공부하는데 있어서 배울 점이 많을 것 같습니다. 개발, 동문과의 소통에 열정적인 멘토님이 진행하시는 거라 더욱 기대가 됩니다. 열심히 참여해 완주하도록 하겠습니다!

**Comment by himitery** [comment]
- 이름: 이학진
- 이메일: himit0131@naver.com
- 자기 소개
    - 소프트웨어학과 2학년으로 재학중인 이학진입니다.
- 스터디에 기대하는 점
    - Javascript에 대해 조금 더 깊게 공부해보고 싶습니다!
    - Express JS로 API를 만드는 과정과 실제로 배포하는 과정을 직접 경험해보고 싶습니다!
    - 무사히 완주하고 소소한 식사자리에 끼는 것!? 😁

**Comment by Wonyeong210** [comment]
- 이름: 이원영
- 이메일: leeoo6436@naver.com
- 짤막한 자기소개
	- 응용컴퓨터공학과 3학년 이원영입니다.
	- 웹에 관심이 생겨서 참여하게 되었습니다.
- 스터디에 기대하는 점
	- 코드 리뷰도 진행한다고 해서 기대가 됩니다.
	- 다른 사람들과 함께 공부를 해나갈 수 있어서 기대가 됩니다.

**Comment by eyabc** [comment]
- 이름: 박은영
- 이메일: bey4314@naver.com
- 짤막한 자기 소개
  - 저는 7개월 된 신입 개발자 박은영입니다.
  - vue.js, java spring boot 기술을 주로 사용합니다.
- 스터디에 기대하는 점
  - 무사히 완주하겠슴당 ^^~!

**Comment by baesumin** [comment]
- 이름: 배수민
- 이메일: qotnals12345@naver.com
- 짤막한 자기 소개
 소프트웨어학과 졸업한 배수민입니다.
 javascript 공부를 위해 지원하게되었습니다.
- 스터디에 기대하는 점
서로 도우며 실력이 늘었으면 좋겠습니다!

**Comment by heewon916** [comment]
- 이름: 김희원
- 이메일: kimhiwon@naver.com
- 짤막한 자기소개: 
   소프트웨어학과 2학년 김희원입니다. 
   javascript 공부뿐만 아니라 배포까지 하려면 어떻게 해야 하나 고민하고 있었는데 이렇게 좋은 기회를 알게 되어 기쁩니다. 
-  스터디에 기대되는 점: 
   같은 목적을 갖고 있는 분들과 함께 공부하며 성장할 생각에 설렙니다.  무사 완주하도록 하겠습니다!

**Comment by JunilHwang** [comment]
## 공지
스터디 신청하신분들은 디스코드 `뱃살포동포동#6018` 친구 추가 해주세요! 스터디 채널에 초대해드리겠습니다 🙇‍♂️

**Comment by kimjaehyeon221** [comment]
- 이름: 김재현
- 이메일: id967@naver.com
- 짤막한 자기 소개
sw융합경제경영전공 2학년 김재현입니다.
이제 막 웹 개발 공부를 하고 있습니다.
-스터디에 기대하는 점
꼭 완주 해보도록 하겠습니다!

**Comment by ghost** [comment]
• 이름: 이수정
• 이메일: qalzm7351@gmail.com
• 짤막한 자기소개:
소프트웨어학과 2학년 이수정입니다. 
웹에 관심이 생겨 이번 방학때 자바스크립트 공부를 목표로 하고 있었는데 관련 스터디가 생겨서 신청합니다.
• 스터디에 기대하는 점: 
같은 목표를 가지신 분들과 함께 공부하며 성장하고 싶습니다.
스터디 완주를 꼭 해내고 싶습니다.

**Comment by kykapple** [comment]
* 이름: 권영기
* 이메일: kykapple@naver.com
* 짤막한 자기소개:
    * 소프트웨어학과 3학년 권영기입니다.
    * 웹 개발에 관심이 있어 지원을 하게 되었습니다.
* 스터디에 기대하는 점:
    * javascript에 대해 더 자세히 공부해보고 싶습니다.
    * 코드 리뷰를 진행해주신다는 점이 기대됩니다!

**Comment by JunilHwang** [comment]
-- 모집이 마감되었습니다. --

**Comment by nerdyinu** [comment]
안녕하세요. 

> -- 모집이 마감되었습니다. --

안녕하세요. 2주전쯤에 저한테 초청이 왓었는데 기말고사기간동안 확인하지 못하고 지금 확인했습니다. 스터디 참가하고 싶은데 가능한지, 혹시 마감됐다면 스터디 그룹에 초청을 다시 해주실 수 있는지 궁금합니다. 감사합니다.

**Comment by JunilHwang** [comment]
@inust33 안녕하세요! 아마 알고리즘 스터디를 말씀하시는 것 같아요! 제가 디스코드로 친구요청 보냈으니 확인해보시면 될 것 같습니다!

**Comment by nerdyinu** [comment]
> @inust33 안녕하세요! 아마 알고리즘 스터디를 말씀하시는 것 같아요! 제가 디스코드로 친구요청 보냈으니 확인해보시면 될 것 같습니다!

감사합니다 확인했습니다! 혹시 자바스크립트 스터디는 마감됐을까요?
