### ISSUE TITLE
[2021년 2학기] DKU Javascript Study Level 01 - 2기 모집

### ISSUE THREAD

**Issue by JunilHwang** [DKU-STUDY/recruit#2]
## 목적
- Javascript 입문자를 위한 강의형 스터디를 모집
- 스터디를 통한 개발자 커뮤니티 구성
- 선후배간의 정보 교류

## 이런 사람들이 참가하면 좋습니다.
- Javascript, 웹 개발 등에 흥미가 있거나 좋아하는 사람
- 프론트엔드 개발자를 목표로 하고 싶은 사람
- React, Vue 같은 프레임워크에 초점을 두는게 아닌 Javascript 자체를 공부해보고 싶은 사람
- 최종적으로 프레임워크를 만들어보고 싶은 사람
- 같이 공부할 사람이 필요한 사람
- 진로 관련 면담 진행

--------------------------------------------
## 스터디 리더 소개
- 블로그: https://junilhwang.github.io/TIL
- github: https://github.com/junilhwang
- 네이버/카카오/우아한형제들/인프런 등 다수의 회사에서 스카웃 제의

### 이력
- 단국대 소프트웨어학과(2013 ~ 2020) 졸업
- [줌인터넷](https://www.zuminternet.com/) 포털개발팀 프론트엔드 파트리더
- Java/SpringBoot/NodeJS/Javascript/Typescript/VueJS 등을 현업에서 사용중인 풀 스택 개발자

### About
- [DKU-STUDY](https://github.com/DKU-STUDY) 멘토
- [우아한 테크캠프 Pro 2](https://edu.nextstep.camp/s/ffeVDScX) 리뷰어 
- [부스트캠프 2020](https://github.com/boostcamp-2020) 프론트엔드 리뷰어
- [부스트캠프 2021](https://github.com/boostcampwm-2021) 프론트엔드 리뷰어

### Articles
- 2019년도 기준 자기소개 겸 발표 문서: http://junil-hwang.com/20191210.pdf
- 2020년 회고: https://junilhwang.github.io/TIL/Review/2020-year/end/
- 2021년 회고: https://junilhwang.github.io/TIL/Review/2021-year/01-First-Quarter/
- 주제별 영상 제공 웹 서비스: https://zuminternet.github.io/ZUM-Pilot-provide-video/
- 크롬 확장프로그램 개발⛏️ 회고: https://zuminternet.github.io/Zum-Chrome-Extension/
- 주니어 프론트엔드 개발자의 채용 프로세스 참여 후기: https://zuminternet.github.io/zum-front-recurit-review/
- Vue SSR 제대로 적용하기 (feat. Vanilla SSR): https://zuminternet.github.io/vue-ssr/
- Vanilla Javascript로 웹 컴포넌트 만들기: https://junilhwang.github.io/TIL/Javascript/Design/Vanilla-JS-Component/
- Vanilla Javascript로 상태관리 시스템 만들기: https://junilhwang.github.io/TIL/Javascript/Design/Vanilla-JS-Store/
- Vanilla Javascript로 가상돔(VirtualDOM) 만들기: https://junilhwang.github.io/TIL/Javascript/Design/Vanilla-JS-Virtual-DOM/
- Vanilla Javascript로 React UseState Hook 만들기: https://junilhwang.github.io/TIL/Javascript/Design/Vanilla-JS-Make-useSate-hook/
--------------------------------------------

### 커리큘럼
- 1주차: 웹에 대한 기본이론 + 간단한 Todo List 만들기
- 2주차: 번들러 조사 및 적용(webpack, parcel)
- 3주차: ExpressJS로 API 서버 만들고 연동하기
- 4주차: 배포하기

### 기타
- (1) 매주 정해진 요일에 온라인 세션 진행
  - 1주차: 스터디에 대한 소개, 미션에 대한 소개 진행
  - 2 ~ 5주차: 미션에 대한 회고, 핵심내용, 좋은점, 아쉬운점 등에 대해 이야기
  - 모든 온라인 세션은 녹화본 제공 예정
- (2) 온라인 세션 후 일주일 동안 미션 진행
- (3) Pull Request 를 올리면 코드 리뷰 진행

### 일정
- 시작: 10/11(월) 예상
- 종료: 11/15(월) 예상

## 참가비
1. 무료로 참가하기
  - 완전무료
2. 유료로 참가하기
  - 5만원 지불 후 완주시 10만원으로 반환
  - 스터디장이 손해보는 장사 😇

## 스터디 참여 방법
- github id가 필요합니다.
- 깃허브 이슈(https://github.com/DKU-STUDY/recruit/issues/2) 에 comment로 참가의사를 남겨주세요.
  - 이름
  - 이메일 혹은 노출되도 무관한 연락처
  - 짤막한 자기 소개
  - 스터디에 기대하는 점
  - [**디스코드**](https://discord.com/) 아이디

**Comment by JunilHwang** [comment]
- 이름: 황준일
- 이메일: junil.h@kakao.com
- 짤막한 자기 소개
  - 저는 현재 [줌인터넷](https://zuminternet.com)에서 파트리더로 근무하고 있는 황준일입니다.
  - 단국대 학생들과 꾸준히 소통하고 싶어서 이러한 스터디를 만들었습니다. 
- 스터디에 기대하는 점
  - 무사 완주 하는 사람이 한 명 쯤은 있겠지!?
- discord 아이디
  - 뱃살포동포동#6018

**Comment by eyabc** [comment]
- 이름: 박은영
- 이메일: bey4314@naver.com
- 짤막한 자기 소개
저는 현재 줌인터넷에서 근무하고 있는 박은영입니다.
저번 기수에 참여 신청을 했으나 스터디에 참여하지 못했습니다. ㅠㅠ 죄송합니다 

- 스터디에 기대하는 점
  - 스터디원들끼리 커뮤니케이션이 많이 이뤄졌으면 좋겠습니다~

**Comment by JunilHwang** [comment]
스터디의 커뮤니케이션 도구로 [디스코드](https://discord.com/)를 이용합니다. 참가 의사가 있으신 분들은 디스코드 계정도 같이 작성해주세요!

**Comment by nyoongoon** [comment]
- 이름: 윤석빈
- 이메일: nyoongoon@naver.com
- 짤막한 자기 소개
  이제 막 취직한 다산에듀 주니어 개발자 윤석빈입니다.. 백엔드 개발자이지만 프론트도 적용할 기회가 많은 것 같아 제대로 공부해보고 싶어졌습니다..!
- 스터디에 기대하는 점 
  많은 정보를 주고 받았으면 좋겠습니다.. ㅎㅎ 잘 부탁드립니다!!!
- 디스코드 아이디 
  nyoongoon#7417

**Comment by Jung-Off** [comment]
* 이름 : 지정온
* 이메일 : lewis1004@naver.com
* 짤막한 자기 소개
이제 막 개발공부를 시작하게 된지 1년 지금까지는 c만 파다가,, 프론트는 어떤 맛 일까 궁금하여서 엄청난 고민끝에 지원을 하게 되었습니다! 
* 스터디에 기대하는 점
코린이.. 이긴하지만 열심히! 그리고 잘! 배워보는 시간이 되었으면 좋겠습니다! 
* 디스코드 아이디
지상#9594

**Comment by cosbi0000** [comment]
* 이름: 김민혁
 * 이메일: cosbi010830@naver.com
 * 짤막한 자기 소개
   아직 학교를 다니고 있습니다. 웹개발에 관심이 생겨서 지원하게 되었습니다. 소프트웨어에 관련된 학과는 아니지만 웹개발에 큰 관심이 생겨 지원하게 되었습니다.
* 스터디에 기대하는 점
  거의 모르는 상태여서 많이 배워갔으면 좋겠습니다. 많은 정보도 얻었으면 좋겠습니다.
 * discord 아이디
   말랑한타조알#6059

**Comment by blueoxygens** [comment]
●이름: 김현진
●이메일: jimmykim1517@gmail.com
●짤막한 자기 소개:
아직 학교에 다니고 있는 대학생입니다.주로 java하고 c만 공부하는데, 남는 시간에 javascript를 배우고 싶어 지원했습니다.
●스터디에 기대하는 점:
javascript 기초를 익힐 수 있으면 좋겠습니다.
●discord 아이디:Mmm#9571

**Comment by Sumin-Hyun** [comment]
- 이름: 현수민
- 이메일 : breath1n015@gmail.com
- 자기소개 :
    안녕하세요, 소프트웨어 관련 학과에 재학중인 학생입니다. 프론트엔드 관련해서 배워보고싶었는데, 기초적인 부분을 접할 수 있는 기회라고 생각되어서 지원하게되었습니다!
- 스터디에 기대하는 점 :
    처음 접해보기떄문에 기초부터 다뤄주시면 정말 감사하겠습니다!
- 디스코드 아이디 : 
    수민#9948

**Comment by eundoit** [comment]
● 이름: 전은수
● 이메일: jysrho12@gmail.com
● 짤막한 자기소개:
현재 소프트웨어학과 휴학 중인 학생입니다. 프론트엔드 배워보고싶었는데 혼자 시작하기가 어려워서 스터디 참여해봅니다! 
● 스터디에 기대하는 점:
열심히 배우겠습니다. 무사 완주하고싶어요!
● discord 아이디: 은두#2379

**Comment by SHee97** [comment]
- 이름 : 조석희
- 이메일 : starberry970310@gmail.com
- 자기소개 :
막학기 다니고 있는 4학년이지만 아직 개발공부는 시작한지 한달도 안 된 초보입니다.
혼자 어떻게 공부해야 할까 고민하던 중에 좋은 공부가 될 것 같아 지원하게 되었습니다.
- 스터디에 기대하는 점 :
개발 내적, 외적으로 많은 걸 배우는 기회가 되면 좋겠습니다. 늦은만큼 더 열심히 배우겠습니다!
- discord 아이디 : ok.cheese#8708

**Comment by ChoiHeekyeong** [comment]
이름: 최희경
이메일:  gmlrud9701@naver.com
자기 소개: 단국대학교 4학년 재학생입니다. JAVA로 안드로이드스튜디오 위주로 해왔는데 웹개발에 관심이 생겨서 자바스크립트를 공부해야겠다고 생각하던 와중에 좋은 프로그램이 생겨서 지원하게 됐습니다.
스터디에 기대하는 점:
자바스크립트를 잘 쓸줄 아는 사람으로 성장하고 싶습니다
디스코드 아이디: 희경#3444

**Comment by j-roh** [comment]
- 이름: 노주연
- 이메일: jy-roh@dankook.ac.kr
- 짤막한 자기 소개
      - 파이썬만 사용해보다가 다른 기관분들께서 자바스크립트를 사용해보라고 하셔서 배우려고 하는 대학원생입니다.
- 스터디에 기대하는 점
      - 처음 배우는 언어이지만, 독학하지 않아도 되고, 다른 사람들이랑 같이 배울 수 있어서 너무 기대됩니다.
- discord 아이디
      - jy-roh#2436

**Comment by copiCat0** [comment]
- 이름 : 이원준
- 이메일 : lwj2627@naver.com
- 자기소개:
소프트웨어학과 3학년 재학생입니다. 최근에 웹 개발에 관심이 생겼고, 공부해보고싶습니다.
작년에 OvearZ에 들어간 적 있습니다
- 스터디에 기대하는점
리액트 프로젝트를 진행중인데, 자바스크립트를 할 줄 모릅니다. 자바스크립트를 공부할 아주 좋은 기회라고 생각합니다!

- discord 아이디
- 원준#9469

**Comment by masterjms** [comment]
●  이름: 장민성

●  이메일:mstoto0319@gmail.com

●  짤막한 자기소개:
    HTML공부하던 중 웹 개발에 대해 더 자세히 배워보고 싶어서 지원했습니다. 1학년 학부생이라 모르는게 많지만 열심히 하겠습니다.
	
● 스터디에 기대하는점
   프론트엔드 개발자에 대한 구체적인 진로를 정할 수 있는 시간이 되었으면 좋겠습니다.

● discord 아이디
   장민성#3286

**Comment by kangjiwon12** [comment]
•이름:강지원
•이메일:kjw5064@naver.com
•짤막한 자기소개:현재 단국대학교 3학년 재학생입니다.개발 공부를 시작한지 얼마 안되서 c언어만 사용해봤습니다. 프론엔드 개발에 관심이 있어서 스터디에 지원하게 됬습니다.
•스터디에 기대하는 점:처음 배우는거여서 차근 차근 알려주셨으면 좋겠습니다.
•discord 아이디:jiwon#8172

**Comment by kimjaehyeon221** [comment]
- 이름 : 김재현

- 이메일 : id967@naver.com

- 자기소개 : 소프트웨어학과 관련 학과에 재학 중입니다. 프론트 엔드 개발에 관심이 생겨 자바스크립트 스터디를 지원하게 되었습니다. 

- 스터디에 기대하는 점: 혼자 프론트엔드 공부를 하다보니 방향을 잡지 못하고 우왕좌왕했습니다. 이번 기회를 통해 많이 배우고 싶습니다. 잘 부탁드립니다! 

- discord 아이디 : 김재현#1952

**Comment by serotonins** [comment]
- 이름: 최지수
- 이메일: shadycally@gmail.com
- 짤막한 자기 소개: 막학기 재학 중입니다. 프로그래밍과는 아니다보니 학과에서 프로그래밍에 대해 아주 약간 접할 수 있었는데 제대로 배워보고 싶어 지원합니다.
- 스터디에 기대하는 점: 잘 배워서 이론만 습득하기보다 활용할 수 있는 능력을 갖추고 싶습니다.
- discord 아이디: js#3211

**Comment by eyabc** [comment]
초대링크 : https://discord.gg/9HRJguUx 
안녕하세요~! 메시지를 보신 분들은 discode 채널에 미리 참여해주세요~!

![image](https://user-images.githubusercontent.com/31977543/136689068-5be2eb94-1535-4c56-9e9b-769df8c17f6c.png)
여기 채널에서 진행됩니다.


닉네임은 : 이름 / githubId 로 변경해주세요
![image](https://user-images.githubusercontent.com/31977543/136689141-e818518a-1723-49bf-bf6d-7ad7f9879328.png)

**Comment by JunilHwang** [comment]
모집 마감합니다!
