### ISSUE TITLE
[2021년 2학기] DKU Javascript Study Level 02 - 1기 모집

### ISSUE THREAD

**Issue by JunilHwang** [DKU-STUDY/recruit#3]
## 목적
- Javascript 중급자를 위한 강의형 스터디를 모집
- 스터디를 통한 개발자 커뮤니티 구성
- 선후배간의 정보 교류

## 이런 사람들이 참가하면 좋습니다.
- Vue, React 등의 프론트엔드 프레임워크를 다뤄본사람
- 프론트엔드 개발자를 목표로 하고 싶은 사람
- React, Vue 같은 프레임워크에 초점을 두는게 아닌 Javascript 자체를 공부해보고 싶은 사람
- 최종적으로 프레임워크를 만들어보고 싶은 사람
- 같이 공부할 사람이 필요한 사람
- 진로 관련 면담 진행

--------------------------------------------
## 스터디 리더 소개
- 블로그: https://junilhwang.github.io/TIL
- github: https://github.com/junilhwang
- 네이버/카카오/우아한형제들/인프런 등 다수의 회사에서 스카웃 제의

### 이력
- 단국대 소프트웨어학과(2013 ~ 2020) 졸업
- [줌인터넷](https://www.zuminternet.com/) 포털개발팀 프론트엔드 파트리더
- Java/SpringBoot/NodeJS/Javascript/Typescript/VueJS 등을 현업에서 사용중인 풀 스택 개발자

### About
- [DKU-STUDY](https://github.com/DKU-STUDY) 멘토
- [우아한 테크캠프 Pro 2](https://edu.nextstep.camp/s/ffeVDScX) 리뷰어 
- [부스트캠프 2020](https://github.com/boostcamp-2020) 프론트엔드 리뷰어
- [부스트캠프 2021](https://github.com/boostcampwm-2021) 프론트엔드 리뷰어

### Articles
- 2019년도 기준 자기소개 겸 발표 문서: http://junil-hwang.com/20191210.pdf
- 2020년 회고: https://junilhwang.github.io/TIL/Review/2020-year/end/
- 2021년 회고: https://junilhwang.github.io/TIL/Review/2021-year/01-First-Quarter/
- 주제별 영상 제공 웹 서비스: https://zuminternet.github.io/ZUM-Pilot-provide-video/
- 크롬 확장프로그램 개발⛏️ 회고: https://zuminternet.github.io/Zum-Chrome-Extension/
- 주니어 프론트엔드 개발자의 채용 프로세스 참여 후기: https://zuminternet.github.io/zum-front-recurit-review/
- Vue SSR 제대로 적용하기 (feat. Vanilla SSR): https://zuminternet.github.io/vue-ssr/
- Vanilla Javascript로 웹 컴포넌트 만들기: https://junilhwang.github.io/TIL/Javascript/Design/Vanilla-JS-Component/
- Vanilla Javascript로 상태관리 시스템 만들기: https://junilhwang.github.io/TIL/Javascript/Design/Vanilla-JS-Store/
- Vanilla Javascript로 가상돔(VirtualDOM) 만들기: https://junilhwang.github.io/TIL/Javascript/Design/Vanilla-JS-Virtual-DOM/
- Vanilla Javascript로 React UseState Hook 만들기: https://junilhwang.github.io/TIL/Javascript/Design/Vanilla-JS-Make-useSate-hook/
--------------------------------------------

### 커리큘럼
- 1주차: React, Vue로 TodoList 만들기
- 2주차: Web Component 구성
- 3주차: 옵저버 패턴 적용
- 4주차: Store 구성

### 기타
- (1) 매주 정해진 요일에 온라인 세션 진행
  - 1주차: 스터디에 대한 소개, 미션에 대한 소개 진행
  - 2 ~ 5주차: 미션에 대한 회고, 핵심내용, 좋은점, 아쉬운점 등에 대해 이야기
  - 모든 온라인 세션은 녹화본 제공 예정
- (2) 온라인 세션 후 일주일 동안 미션 진행
- (3) Pull Request 를 올리면 코드 리뷰 진행

### 일정
- 시작: 10/11(월) 예상
- 종료: 11/15(월) 예상

## 참가비
1. 무료로 참가하기
    - 완전무료
2. 유료로 참가하기
    - 5만원 지불 후 완주시 10만원으로 반환
    - 스터디장이 손해보는 장사 😇

## 스터디 참여 방법
- github id가 필요합니다.
- 깃허브 이슈(https://github.com/DKU-STUDY/recruit/issues/3) 에 comment로 참가의사를 남겨주세요.
    - 이름
    - 이메일 혹은 노출되도 무관한 연락처
    - 짤막한 자기 소개
    - 스터디에 기대하는 점
    - [**디스코드**](https://discord.com/) 아이디

**Comment by JunilHwang** [comment]
- 이름: 황준일
- 이메일: junil.h@kakao.com
- 짤막한 자기 소개
  - 저는 현재 [줌인터넷](https://zuminternet.com)에서 파트리더로 근무하고 있는 황준일입니다.
  - 이 스터디의 리더입니다.
  - 단국대 학생들과 꾸준히 소통하고 싶어서 이러한 스터디를 만들었습니다. 
- 스터디에 기대하는 점
  - 무사 완주 하는 사람이 한 명 쯤은 있겠지!?
- **디스코드 아이디**
  - 뱃살포동포동#6018

**Comment by JunilHwang** [comment]
스터디의 커뮤니케이션 도구로 [디스코드](https://discord.com/)를 이용합니다. 참가 의사가 있으신 분들은 디스코드 계정도 같이 작성해주세요!

**Comment by pul8219** [comment]
- 이름: 박유림
- 이메일 혹은 노출되도 무관한 연락처: pul8219@naver.com
- 짤막한 자기 소개
    - 프론트엔드 개발자 취직을 준비중인 단국대학교 소프트웨어학과 학생입니다.
    - 프론트엔드 입사과제나 JavaScript 공부를 진행할 때 혼자 공부하려니 어렵더라구요. 함께 공부하고싶어 스터디를 신청하게되었습니다.
- 스터디에 기대하는 점: Javascript 자체를 열심히 학습하여 최종적으로 프레임워크를 만들어볼 수 있다는게 기대가 됩니다.
- 디스코드 아이디 Park Yurim#6975

**Comment by dosimpact** [comment]
- 이름: 김도영
- 이메일: ypd03008@gmail.com
- 짤막한 자기 소개.
    웹프론트 취업 준비중인 4학년 김도영 입니다 ~
   SW마에스트로-12th 연수중입니다
- 스터디에 기대하는 점   
이번기회에 뷰를 한번써보고, 선후배님들과 네트워킹 하는 자리가 되길 바랍니다. 
- 디스코드 아이디
김도영#3934

**Comment by developerjhp** [comment]
+ 이름: 박진현
+ 이메일: developerjhp@gmail.com
+ 짤막한 자기 소개.
  + 프론트엔드 취준중인 산업공학과 학생입니다
+ 스터디에 기대하는 점
  + 항상 리액트만 썼었는데 뷰도 사용해보고 제가몰랐던 많은 부분들을 알 수 있게되면 좋겠습니다. 
+ 디스코드 아이디
  + 박진현#8159

**Comment by nerdyinu** [comment]
- 이름: 정인우
- 이메일: inust33@gmail.com
- 짤막한 자기소개
   프론트엔드로 취준을 준비하는  4학년 정인우입니다.  이번년도에 융합전공으로 전입하여 공부를 시작하였습니다. 
- 스터디에 기대하는 점
   자바스크립트에서 좋은코드가 무엇인지 알게 됐으면 좋겠습니다.
- 디스코드 아이디
   정인우#1944

**Comment by Wongyu-Shin** [comment]
* 이름: 신원규
* 이메일: won7963kr@gmail.com
* 짤막한 자기 소개
  * 웹 개발 취업 준비를 위해 공부중인 비전공자 개발지망생입니다.
  * 강력한 기능을 자랑하는 프레임위크도 좋지만, 좀더 기본적인 CS 지식에 대해서 관심이 큽니다.
 * 스터디에 기대하는점
  활발한 소통이 있었으면 좋겠습니다!
* 디스코드 아이디
 nqmu#6870

**Comment by chogyejin** [comment]
-  이름 : 조계진
-  이메일 : whrpwls96@naver.com
-  짤막한 자기 소개
    -  웹 프론트엔드 직무를 희망하는 4학년입니다.
-  스터디에 기대하는 점
    -  자바스크립트 자체에 대한 이해를 높이고, 실제 현업에서 뭐가 필요한지 배워가고 싶습니다.
-  디스코드 아이디
    - 조계진#6762

**Comment by JunilHwang** [comment]
모집 마감합니다!
